spring.application.name=heroes-api
spring.datasource.url=jdbc:mysql://localhost:3306/heroes_db
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hacemos que Hibernate nos actualice las tablas en lugar de tirarlas y crearlas, por si hay datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
